default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sacc_development
test:
  <<: *default
  database: sacc_test

production:
  <<: *default
  database: sacc_production
  username: sacc
  password: <%= ENV['SACC_DATABASE_PASSWORD'] %>
